### ISSUE TITLE
Request: async example

### ISSUE THREAD

**Issue by OrangeDog** [nodejs/node-addon-examples#1]
An example that calls a callback asynchronously would be very valuable.

I imagine getting async behaviour correct is what most addon developers are going to be worried about, i.e. not blocking the Node event loop.
I at least really don't know where to start with it.

**Comment by paulhauner** [comment]
+1 I am trying to implement this at the moment and am _struggling_

**Comment by paulhauner** [comment]
I just created an example. It's lightweight and it works.

https://github.com/paulhauner/example-async-node-addon

**Comment by NickNaso** [comment]
Hi everyone, now there is an example about asynchronous operation here: [https://github.com/nodejs/node-addon-examples/tree/master/async_pi_estimate](https://github.com/nodejs/node-addon-examples/tree/master/async_pi_estimate)

**Comment by mhdawson** [comment]
Since there is now an example, I'm going to close this, please let me know if that is not the right thing to do.
