### ISSUE TITLE
v0.11.13-pre and V8 3.25.30 refurbishing

### ISSUE THREAD

**Issue by rimmartin** [nodejs/node-addon-examples#10]
Hi,

I upgraded all but 7_factory_wrap &  8_passing_wrapped.  Get the 

```
 Assertion `handle->InternalFieldCount() > 0' failed.
```

For the rest I can provide patch files.  The changes are for V8 and node master branches as of today.

**Comment by Trott** [comment]
@nodejs/n-api Since 0.11 is unsupported, even as examples in this repository (which seems to still support 0.10 and 0.12, if I understand correctly?), should this be closed?

Regardless of the answer, is it worth doing a quick triage of the 35 open issues here to see which ones are still issues?

**Comment by gengjiawen** [comment]
You can close this. I recently has removed the deprecated example.

> Regardless of the answer, is it worth doing a quick triage of the 35 open issues here to see which ones are still issues?

+1
