### ISSUE TITLE
Remove deprecated folder like node_0.10

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-addon-examples#102]
Remove them since they are deprecated or archive them in separate branch.

**Comment by mhdawson** [comment]
I think it was good to have the older examples for a while, but they have been deprecated for quite a long time now so I'd be +1 on removing them.  Maybe we should remove node_0.12 as well?

**Comment by NickNaso** [comment]
Hi everyone,
I agree on removing the old examples, but I think that we need to close the old issues too. What's your opinion about that?

**Comment by gengjiawen** [comment]
> Hi everyone,
> I agree on removing the old examples, but I think that we need to close the old issues too. What's your opinion about that?

+1
