### ISSUE TITLE
Should CI test include various linux distros.

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-addon-examples#105]
I am working on a PR adding CI: https://github.com/nodejs/node-addon-examples/pull/104.

Should we add various linux distros test like CentOs, debian, ubuntu like https://github.com/nodesource/distributions/blob/master/.circleci/config.yml

**Comment by mhdawson** [comment]
Running on different OS/distros would give us more coverage.  We do already have addon test in the core Node.js tests as well as this CI job for node-addon-api -> https://ci.nodejs.org/job/node-test-node-addon-api-new/ which runs across all LTS + Current Node.js versions and across the supported platforms for Node.js.

My feeling is that is probably good enough for platform/distro coverage until we run into a case were an example is broken on a specific platform/OS and it's not caught by one of those other 2 existing jobs.
