### ISSUE TITLE
node-gyp build issue

### ISSUE THREAD

**Issue by alokpandey** [nodejs/node-addon-examples#11]
Hi,

I have been working with Node addon and everything was working great until today when I started getting issues in node-gyp build. my addon compiles successfully but hangs forever and doesn't create .node file. the last line I see in console is SOLINK_MODULE(target) Release/obj.target/something.node. It simply hangs there for ever.

I did lot of search online but couldn't find any help.

Thanks

**Comment by tk120404** [comment]
@alokpandey Can you please close this issue if this is not issue any more?

**Comment by NickNaso** [comment]
Hi everyone, this is a very old issue, so I'm closing it, but feel free to reopen in case you believe that we need to continue working on it.
