### ISSUE TITLE
Can i bind nan.h with C++ MySQL Driver?

### ISSUE THREAD

**Issue by hadihammurabi** [nodejs/node-addon-examples#110]
I want to create very fast (performance) service using NodeJS. In some conditions, i meet big database operation. I want to do this using C++.

**Comment by NickNaso** [comment]
Hi @hadihammurabi, 
You can  find a native add-on that binds the MySQL Driver here: https://github.com/mmod/nodamysql . This seems to be an old project that use the v8 API directly, but you can use as an example to do your work through `nan.h`. In alternative you can consider to use `node-addon-api` that is a C++ wrapper over N-API.

**Comment by hadihammurabi** [comment]
> Hi @hadihammurabi,
> You can find a native add-on that binds the MySQL Driver here: https://github.com/mmod/nodamysql . This seems to be an old project that use the v8 API directly, but you can use as an example to do your work through `nan.h`. In alternative you can consider to use `node-addon-api` that is a C++ wrapper over N-API.

thankyou for replying

i will check it soon

**Comment by NickNaso** [comment]
Hi @hadihammurabi,
is it possible close this issue or do you need some other help?
