### ISSUE TITLE
Add clang-format to this repo ?

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-addon-examples#111]
Any thought, I can work on this :)

**Comment by mhdawson** [comment]
I'm +1 for that.  Would be good to make it either consistent with what we do in Node core for formatting or get an agreement that that does not make sense.  Long way of saying is that I think it would be good to get some feedback from the Node core C++ developers on the format.

I'm thinking we might want to use the same for node-addon-api as well...

**Comment by gengjiawen** [comment]
> Would be good to make it either consistent with what we do in Node core for formatting

I am planing copy that config.

> ong way of saying is that I think it would be good to get some feedback from the Node core C++ developers on the format.

Currently we have no group like @nodejs/cpp . Maybe we can develop a unify cpp style and share it across repos.

**Comment by legendecas** [comment]
AFAIK clang-format did not enabled on node core too though `.clang-format` presents there. Would there be possible of enabling it in node core?

**Comment by gengjiawen** [comment]
> AFAIK clang-format did not enabled on node core too though .clang-format presents there

Nope, it's used. Only test for related change.

> Would there be possible of enabling it in node core?

Not likely because of maintain issue. See https://github.com/nodejs/node/issues/25955。
