### ISSUE TITLE
Working examples for Node v0.11.13?

### ISSUE THREAD

**Issue by MartinMa** [nodejs/node-addon-examples#12]
I checked out `1_hello_world` on the v0.11 branch, but the example doesn't compile (Windows 7, VS 2012).

Check out the following screenshot and error list:

![node_error](https://cloud.githubusercontent.com/assets/123297/4201224/e6f165c4-381b-11e4-94c3-c6e6f4863177.jpg)

```
Error   1 error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
Error   2 error C2143: syntax error : missing ',' before '&'
Error   3 error C2039: 'Close' : is not a member of 'v8::HandleScope'
Error   4 error C2039: 'New' : is not a member of 'v8::String'
Error   5 error C3861: 'New': identifier not found
Error   6 error C2039: 'NewSymbol' : is not a member of 'v8::String'
Error   7 error C2664: 'v8::FunctionTemplate::New' : cannot convert parameter 1 from 'v8::Handle<T> (__cdecl *)(const int)' to 'v8::Isolate *'  c:\users\mmaedler\documents\visual studio
Error   8 error C2227: left of '->GetFunction' must point to class/struct/union/generic type
Error   9 error C3861: 'NewSymbol': identifier not found
```

Is there anything I'm missing? The other examples for **node-v0.10.31** did compile fine. All I could figure out is, that `Arguments` seems to be a member of the namespace `v8::internals` now.

**P.S.** It does indeed compile against **node-v0.11.3**. But I need my module to run with **v0.11.13**. Is this possible?

Thanks in advance

**Comment by tk120404** [comment]
@MartinMa Can you please close this issue if this is not an issue any more?

**Comment by gengjiawen** [comment]
Close this since this has been resolved.

**Comment by MartinMa** [comment]
@gengjiawen It has been resolved in the sense that I changed the example code given the information linked above so that it works for me (personally). I didn't close the issue, because the correct way of solving this issue would be updating the examples in this repository on the respective branch. But I believe node 0.11.x is irrelevant by now, so I guess it is ok like this.
