### ISSUE TITLE
question about 6_object_wrap

### ISSUE THREAD

**Issue by xujihui1985** [nodejs/node-addon-examples#13]
I have a question about Persistent, in the sixth example

```
void MyObject::Init(Handle<Object> target) {
  // Prepare constructor template
  Local<FunctionTemplate> tpl = FunctionTemplate::New(New);
  tpl->SetClassName(String::NewSymbol("MyObject"));
  tpl->InstanceTemplate()->SetInternalFieldCount(1);
  // Prototype
  tpl->PrototypeTemplate()->Set(String::NewSymbol("plusOne"),
      FunctionTemplate::New(PlusOne)->GetFunction());

  Persistent<Function> constructor = Persistent<Function>::New(tpl->GetFunction());
  target->Set(String::NewSymbol("MyObject"), constructor);
}
```

why the constructor need to be defined as Persistent Handler instead of Local handler? I have tried to use Local<Function> and it also work.

**Comment by Trott** [comment]
This looks like it can be closed. Feel free to comment (or re-open if GitHub lets you) if you think it should remain open. Thanks! h/t @styfle

**Comment by xujihui1985** [comment]
sure, this can be closed, thanks a lot for answer the question
