### ISSUE TITLE
inconsistent Napi::HandleScopes

### ISSUE THREAD

**Issue by mvduin** [nodejs/node-addon-examples#135]
Based on [the documentation](https://github.com/nodejs/node-addon-api/blob/master/doc/object_lifetime_management.md), a Napi::HandleScope at the top-level of a method is superfluous ("The lifespan for the default scope is tied to the lifespan of the native method call. The result is that, by default, handles remain valid and the objects associated with these handles will be held live for the lifespan of the native method call.").  A few examples however use Napi::HandleScope or Napi::EscapableHandleScope in situations where their purpose is unclear:

* [6_object_wrap/node-addon-api/myobject.cc](/nodejs/node-addon-examples/blob/master/6_object_wrap/node-addon-api/myobject.cc)
* [7_factory_wrap/node-addon-api/myobject.cc](/nodejs/node-addon-examples/blob/master/7_factory_wrap/node-addon-api/myobject.cc)
* [8_passing_wrapped/node-addon-api/myobject.cc](/nodejs/node-addon-examples/blob/master/8_passing_wrapped/node-addon-api/myobject.cc)
* [async_pi_estimate/node-addon-api/async.cc](/nodejs/node-addon-examples/blob/master/async_pi_estimate/node-addon-api/async.cc)
* [function-reference-demo/node-addon-api/src/native-addon.cc](/nodejs/node-addon-examples/blob/master/function-reference-demo/node-addon-api/src/native-addon.cc)

All four of these use a HandleScope in their Init function, yet none of the other examples do.  The first three use one in a constructor, yet neither function-reference-demo nor [object-wrap-demo](/nodejs/node-addon-examples/blob/master/object-wrap-demo/node-addon-api/src/object_wrap_demo.cc) uses one in theirs. 7_factory_wrap uses an EscapableHandleScope in its NewInstance but 8_passing_wrapped  does not.  async_pi_estimate uses a HandleScope in its OnOK method but [napi-asyncworker-example](napi-asyncworker-example/node-addon-api/src/SimpleAsyncWorker.cc) does not.

Since I think the documentation is not terribly clear on when a HandleScope is required, it is especially important that the examples are consistent about their usage.  If there's a good reason to use one in any of these examples, it should be adorned by a comment explaining why a HandleScope is used there.

**Comment by mhdawson** [comment]
@mvduin its a good point. Have you tried removing the HandleScope were it looks like they may not be needed to see if the example still runs ok?  Since for example the 6_object_wrap napi version does not use a scope I'm thinking we don't need it in the node-addon-api version either. 

In any case where there is no scope used in the napi version of the example we should not need one in the node-addon-api version.  @mvduin are you interested in creating a PR to fix?

**Comment by jschlight** [comment]
There's additional discussion on issue https://github.com/nodejs/node-addon-examples/issues/142.

The consensus is that the HandleScopes are not required in the N-API examples.

There's additional documentation here: https://github.com/nodejs/node-addon-api/blob/master/doc/object_lifetime_management.md

**Comment by gabrielschulhof** [comment]
`git grep -niH scope | grep '\.c' | grep -v nan` reveals all handle scope usage – and all of it superfluous at first glance.

**Comment by mhdawson** [comment]
Resolved by https://github.com/nodejs/node-addon-examples/pull/144, closing
