### ISSUE TITLE
napi-asyncworker-example missing scope

### ISSUE THREAD

**Issue by rynz** [nodejs/node-addon-examples#142]
https://github.com/nodejs/node-addon-examples/blob/dc86a662c27c5732e069e1c19d3b7a8e74e86d29/napi-asyncworker-example/node-addon-api/src/SimpleAsyncWorker.cc#L13-L16

This seems to be the only example that doesn't call:
```
Napi::HandleScope scope(Env());
```

Should this example include that too?

**Comment by gabrielschulhof** [comment]
@rynz actually, it should be the other way around. Node.js ensures that all scopes are present by the time the `OnOK`/`OnError` callbacks get called. Thanks for noticing the discrepancy!

We have additional documentation here: https://github.com/nodejs/node-addon-api/blob/master/doc/object_lifetime_management.md

**Comment by rynz** [comment]
@gabrielschulhof thank you!

**Comment by gotnone** [comment]
Can someone who is more familiar with this than I am check to see if there is still bad example code in  node-addon-api/doc/async_worker.md  It appears that the OnOK example is using the Napi::HandleScope when it is not necessary.

Thanks
