### ISSUE TITLE
Factory Wrap example correct?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-examples#143]
I could not get the ObjectWrap Factory example [myobject.cc](https://github.com/nodejs/node-addon-examples/blob/master/7_factory_wrap/node-addon-api/myobject.cc) running, because `env.SetInstanceData()` and `env.GetInstanceData()` methods do not exist.

Should this example work, am I missing something?

**Comment by qxred** [comment]
make sure these values are correct in package.json:
  
```
"engines": { "node": ">= 14.0.0" },
  "dependencies": {
    "bindings": "~1.2.1",
    "node-addon-api": "^3.0.0"
  },

```

**Comment by bsrdjan** [comment]
Thanks, already fixed by updating NAPI version in my Cmake script.
