### ISSUE TITLE
How to make callback after ```uv_async``` is occures? 

### ISSUE THREAD

**Issue by vit1251** [nodejs/node-addon-examples#148]
I review code in https://github.com/nodejs/node-addon-examples/blob/master/3_callbacks/napi/addon.cc and add some ```uv_async``` or ```uv_timer``` callback on main ```uv_loop``` and when it occure I want make callback.

Could I ask you please make another one example or explain here how to invoke callback after ```uv_timer```?

Example (N-API pseudocode):

```
/**
 * 
 */
uvCallback(some_struct_t *data)
{
    pthread_mutex_lock(data->lock)

    // What I should make there napi_call_function or make_callback or else ...
    ...
}

SetCallback( env, cb )
{
   some_stuct_t *data;
   data.cb = cb;
   // Start another one thread process with result in some_struct_t ...
   napi_get_uv_loop(env, loop);
   uv_timer(loop, uvCallback, 1000); // Invoke uvCallback on main Node loop every 1000 sec.
}
```

Example on JavaScript (psedocode):

```
from lib from ...

lib.SetCallback((data) => {
    console.log(`--- per last second we receive ---`);
    console.log(data);
});

lib.StartProcessingInLibraryThreadPoll();
```

**Comment by mhdawson** [comment]
We don't necessarily want to encourage use  of the uv structures as N-API stability does not apply to them. (although we acknowledge that changes are less frequent).  For that reason I don't think we'd want to add an example for N-API, node-addon-api

**Comment by vit1251** [comment]
@mhdawson you may provide way (i.e. uv_async/uv_poll wrapper) to watch on async operation complete on socket events and other combination. You probably right that I can start my own thread start in them libuv and make threadsafe callback but it in some prototype overhead and require additional sync operation create parameter queue's and other operations.

**Comment by mhdawson** [comment]
Have you looked at the [ThreadSafe](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md ) functions  in terms of the thread safety side? 

I do understand the desire to use  uv_async/uv_poll for socket events but was just warning that you don't get the ABI stability guarantees, and for that reason we'd not want to promote that through examples.

**Comment by vit1251** [comment]
@mhdawson it just looks like (use uv_pool/uv_async mechanism) using the main (same as Node) thread and it is strange to use the term thread-safe. In any case, I actually start use a separate thread right now, so the whole issue is resolved. Thank for support.
