### ISSUE TITLE
Enable github pages for this repo.

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-addon-examples#150]
@mhdawson Looks like we need to enable gh-pages in `Settings` Panel (`GitHub Pages` Section). (I don't have the permission).

_Originally posted by @gengjiawen in https://github.com/nodejs/node-addon-examples/pull/149#issuecomment-664098086_

cc @nodejs/addon-api 

PS: http://www.gengjiawen.com/node-addon-examples (on my fork)

**Comment by mhdawson** [comment]
I think it is enable (just checked) and I can see the content at: https://nodejs.github.io/node-addon-examples/

**Comment by mhdawson** [comment]
Maybe I'm mis-understanding the issue?
