### ISSUE TITLE
Share memory between worker threads

### ISSUE THREAD

**Issue by Patick-Bateman** [nodejs/node-addon-examples#190]
Hi. I'm trying to implement a native add-on that act as a "queryable cache". Cache can be partially invalidated/updated, and can be accessed by each separate thread. So each thread will be able to do queries agains same cache, not a copy of it. Is this possible with NAPI?

**Comment by mhdawson** [comment]
Believe this was answered in https://github.com/nodejs/node-addon-api/issues/1057, closing. Please let us know if you think that was not the right thing to do.
