### ISSUE TITLE
returning synchronous array in c++ addon

### ISSUE THREAD

**Issue by Mohamadhj** [nodejs/node-addon-examples#194]
Hello everyone,

I have a c++ code that I'm using nan to be able to implement it in nodejs environment. The problem is, my code has an while loop and wants to send an array for each loop to the nodejs, but I can only send one array in the addon with args.GetReturnValue.Set() or info.GetReturnValue.Set(). Is there a way to continously send data rather than just returning one value at the end of the addon?

Appreciating any help.

**Comment by mhdawson** [comment]
I think you likely want to use a  [ThreadSafe Function](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md#thread-safe-functions) to pass data back to the main thread each time you want to send data

**Comment by Mohamadhj** [comment]
@mhdawson It worked like you said. but it took sometime for me get familiarized with what Threadsafe Functions are and how to implement them.
Thank you so much for the help!

**Comment by Mohamadhj** [comment]
@mhdawson  I have a question, can we still use the Threadsafe function using only C addon, i.e include <node_api.h> and not <napi.h> and thus not relying on C++ classes like Napi:Function, Napi:Value , and so on? thank you for the help!

**Comment by mhdawson** [comment]
I think you can use the Threadsafe APIs in C, @gabrielschulhof do you know if we have any examples of that?

**Comment by Mohamadhj** [comment]
@mhdawson  Thanks, I found a Threadsafe example in C. But I have a question: I want to do two callbacks as opposed to one in the javascript callback, Like this:
test.startThread((theprime) =>{
   msg.payload=theprime;node.send(msg);})
(I'm using Node-RED to send a message across)
Is this possible ? because we're only calling one callback:

**Comment by Mohamadhj** [comment]
@mhdawson Nevermind I used the curly braces (javascript newbie here)

**Comment by mhdawson** [comment]
> @mhdawson Nevermind I used the curly braces (javascript newbie here)

good to hear you have what you need. Can this be closed?

**Comment by Mohamadhj** [comment]
@mhdawson Yes, I will close it now.

**Comment by mhdawson** [comment]
When you say crashed do you mean a SIGSEGV or running out of memory?  Off the top of my head I can't see why more than 6 would be a problem.
