### ISSUE TITLE
Update to 3.17.x API

### ISSUE THREAD

**Issue by trevnorris** [nodejs/node-addon-examples#2]
I'm in the process of updating node to v8 3.17. This requires a few API changes to these examples. You can track the bug here: https://github.com/joyent/node/pull/5077

Don't have the commit up yet with the changes to api docs, but will soon.

**Comment by pyros2097** [comment]
This is really old maybe someone has to close this issue?

**Comment by trevnorris** [comment]
Yup. Thanks.
