### ISSUE TITLE
Object wrap Init function

### ISSUE THREAD

**Issue by rupnikj** [nodejs/node-addon-examples#20]
In the object wrap examples for node 0.12 there is no HandleScope in the Init function, but you use a Local handle. Is this a bug or on purpose? Great examples by the way, very instructive!

```
void MyObject::Init(Handle<Object> exports) {
  Isolate* isolate = Isolate::GetCurrent();

  // Prepare constructor template
  Local<FunctionTemplate> tpl = FunctionTemplate::New(isolate, New);
```

**Comment by JCMais** [comment]
The scope is now handled by Isolates: http://izs.me/v8-docs/classv8_1_1Isolate.html

**Comment by jas0n1ee** [comment]
I got the same question here. Actually on the [api website](https://nodejs.org/docs/latest/api/addons.html#addons_wrapping_c_objects) they use these codes:
```js
void MyObject::Init(Local<Object> exports) {
  Isolate* isolate = exports->GetIsolate();
  ...
```
But I dont find `GetIsolate()` function in Local<Object> with node 0.12

**Comment by JCMais** [comment]
@jas0n1ee the current api docs is for node.js v4, which uses a newer version of v8. v0.12 docs are here https://nodejs.org/docs/latest-v0.12.x/api/addons.html. I recommend you to not use those methods directly, but instead use [NAN](https://github.com/nodejs/nan).

**Comment by jas0n1ee** [comment]
@JCMais Thanks! I'm new to Nodejs and addon. That's great help!

**Comment by gengjiawen** [comment]
It's added now 
https://github.com/nodejs/node-addon-examples/blob/fbf4fdd8314026fd801ad0a8d93a725e1f8adc2f/6_object_wrap/nan/myobject.cc#L13
