### ISSUE TITLE
Node.js C++ Addon Documentation

### ISSUE THREAD

**Issue by ann--b** [nodejs/node-addon-examples#201]
The above [documentation](https://nodejs.org/docs/latest/api/addons.html#hello-world)  refers the reader to this repo for the examples.  But the first hello.cc example in the documentation doesn't match the 1_hello_world/node-addon-api example.  The docs include <node.h> and the repo cc file includes <napi.h>.  The repo file include line was added 5 years ago.  I don't know which code is the most recent.  I'm about to start reading the Node API Resource so maybe I can figure it out.

**Comment by ann--b** [comment]
I think the Node.js documentation is using Node-API which is built into Node, and these examples are using the node-addon-api package.   The Node API Resource did mention that not using this package will require additional coding, so that's why the code doesn't match.

**Comment by NickNaso** [comment]
Hi @ann--b,
Node-API is a C ABI stable API exported from the Node.js core and its documentation is in the core documentation https://nodejs.org/docs/latest/api/n-api.html. `node-addon-api` is a C++ wrapper around Node-API api.
The [Node Addons Examples](https://github.com/nodejs/node-addon-examples) repo contains some examples written in `nan`, `Node-API` and `node-addon-api` if you need the example that use Node-API you should see in the `napi` folder.

**Comment by ann--b** [comment]
Thank you @NickNaso.  As a beginner I don't think I'm ready for the Node API and the core documentation.  I will study the node-addon-api examples for now.
