### ISSUE TITLE
Failed to compile 2_function_arguments with node v.0.10

### ISSUE THREAD

**Issue by imyawar** [nodejs/node-addon-examples#29]
user1@ubuntu:~/node-addon-examples/2_function_arguments/node_0.10$ npm install

> function_arguments@0.0.0 install /home/user1/node-addon-examples/2_function_arguments/node_0.10
> node-gyp rebuild

make: Entering directory `/home/user1/node-addon-examples/2_function_arguments/node_0.10/build'
  CXX(target) Release/obj.target/addon/addon.o
../addon.cc:5:16: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
../addon.cc:5:20: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../addon.cc:5:40: error: expected ‘,’ or ‘...’ before ‘<’ token
../addon.cc: In function ‘void Add(int)’:
../addon.cc:7:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
../addon.cc:7:28: note: candidates are:
/home/user1/.node-gyp/0.10.40/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/home/user1/.node-gyp/0.10.40/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/home/user1/.node-gyp/0.10.40/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
/home/user1/.node-gyp/0.10.40/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../addon.cc:9:7: error: ‘args’ was not declared in this scope
../addon.cc:14:8: error: ‘args’ was not declared in this scope
../addon.cc:19:17: error: ‘args’ was not declared in this scope
../addon.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../addon.cc:28:32: error: invalid conversion from ‘void (*)(int)’ to ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’ [-fpermissive]
/home/user1/.node-gyp/0.10.40/deps/v8/include/v8.h:2259:34: error:   initializing argument 1 of ‘static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::InvocationCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>)’ [-fpermissive]
make: *** [Release/obj.target/addon/addon.o] Error 1
make: Leaving directory `/home/user1/node-addon-examples/2_function_arguments/node_0.10/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user1/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.2.0-29-generic
gyp ERR! command "node" "/home/user1/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user1/node-addon-examples/2_function_arguments/node_0.10
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! function_arguments@0.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the function_arguments@0.0.0 install script.
npm ERR! This is most likely a problem with the function_arguments package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls function_arguments
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-29-generic
npm ERR! command "/home/user1/.nvm/v0.10.40/bin/node" "/home/user1/.nvm/v0.10.40/bin/npm" "install"
npm ERR! cwd /home/user1/node-addon-examples/2_function_arguments/node_0.10
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user1/node-addon-examples/2_function_arguments/node_0.10/npm-debug.log
npm ERR! not ok code 0

**Comment by winfinit** [comment]
If your goal is to make it work, please use NAN instead, that will compile fine for you, it looks like this example was committed incorrectly, as code in it for version 0.12, because FunctionCallbackInfo in v8 was introduces with 0.11

**Comment by winfinit** [comment]
looks like this example was stumped, please reference this page for working example with function arguments: https://nodejs.org/docs/v0.10.40/api/addons.html#addons_function_arguments

pull request for this was submitted (https://github.com/nodejs/node-addon-examples/pull/31)

**Comment by rvagg** [comment]
should be fixed now
