### ISSUE TITLE
[COMMENT] NAN 1.x support

### ISSUE THREAD

**Issue by winfinit** [nodejs/node-addon-examples#34]
with release of NAN 2.x, nodejs version must be >= 0.10.29, so i think it is beneficial to keep examples for both of the versions of nan, would you consider to put back nan_1.x alone with nan_2.x if I will make another pull request? 

for example ubuntu trusty comes with 0.10.25
http://packages.ubuntu.com/search?keywords=nodejs&searchon=names&suite=trusty&section=all

**Comment by rvagg** [comment]
https://github.com/nodejs/nan/pull/399
