### ISSUE TITLE
adding example for making a callback from another thread

### ISSUE THREAD

**Issue by karimcitoh** [nodejs/node-addon-examples#41]
Hi there! Maybe this is not really necessary. But I think I am kind of stuck in there. And it's really hard to find an example of this.

Just a suggestion :)

**Comment by sam-github** [comment]
You can't make callbacks from other threads, but this may help you: https://github.com/nodejs/nan#asynchronous-work-helpers

**Comment by karimcitoh** [comment]
sorry for the late answer, but that indeed helped me and solved my problem!
