### ISSUE TITLE
Examples out of date

### ISSUE THREAD

**Issue by jasnell** [nodejs/node-addon-examples#46]
All of the Addon examples are out of date. We need v4, v5 and soon v6 examples. The most recent appear to be v0.12

**Comment by rvagg** [comment]
v4 and v5 should be the same, we need to figure out a way of separating these into logical groups of major API changes instead of having a directory for each of them. Perhaps the README is enough for documenting this?

**Comment by jasnell** [comment]
Perhaps simply organized by the major version in which the API changed? So
we had a major change in v4, we'd have a v4 folder. If it changes in v6
we'd have a v6 folder... Etc

**Comment by saprative** [comment]
@rvagg  I can write the examples for v4 and create a v4 folder. Can you be a little more specific about which examples I need to change as there are many of them.

**Comment by rvagg** [comment]
@saprative to be consistent we should do all of them, make a new folder "node_4.x" in each of the example directories and put in the code from the addons documentation from core. You'll have to do some editing to make them format properly and present nicely but it's not hard.

**Comment by kelthenoble** [comment]
I'm just starting out in C++ & pretty decent in node.js, but I'll help where ever i can.

**Comment by oncletom** [comment]
Should we rather rely on git branches instead of folders?

I suppose it can be harder to fix shared typos and bugs across various branches though.

**Comment by italoacasas** [comment]
I'm going to start working on this issue, i'll going to start for the first example, is someone is working on that one please 🖐... 

- I'm going to create a folder `node_4.x`

**Comment by italoacasas** [comment]
@rvagg @jasnell  the first example work with v4.x, maybe the solution is to rename the folder `node_0.12` for something more informative like `node_0.12-4.x`, I'll wait for your feedback...

**Comment by peteyy** [comment]
@italoacasas I was considering the same thing, maybe label that differently after trying with the current node versions, do we need to make sure it works only with the LTS versions, or also with node v5?

**Comment by italoacasas** [comment]
all the examples work with the `v5` version too

**Comment by tomgco** [comment]
> I'm going to start working on this issue, i'll going to start for the first example, is someone is working on that one please 🖐...
> 
> I'm going to create a folder node_4.x

Hey @italoacasas, any luck with the v4, v5 versions? I am also looking to have a crack at these and get things back up to date.

**Comment by vaibhav93** [comment]
@tomgco Is there anything I can do to help with your [PR](https://github.com/nodejs/node-addon-examples/pull/49). The documentation needs to be updated I guess.

**Comment by tomgco** [comment]
> @tomgco Is there anything I can do to help with your PR. The documentation needs to be updated I guess.

#49 is pretty much done, just waiting on some more "LGTM"'s, which documentation are you referring too? I guess the only other thing that I missed out in my PR is to update the readme with information that 4.x applies to 5.x as well.

**Comment by vaibhav93** [comment]
Yes. I was talking about the readme.
