### ISSUE TITLE
EventEmitter

### ISSUE THREAD

**Issue by gagle** [nodejs/node-addon-examples#5]
Hi,

Is it possible to add another example showing how to emit events from the c++ land?

[Here's](https://github.com/bnoordhuis/node-event-emitter) an example done by bnoordhuis 2 years ago. Maybe you could rewrite it for v0.10 and v0.11?

The basic idea is to expose a c++ class which inherits from ObjectWrap and internally calls to the `emit` function and in the js code inherit from EventEmitter.

**Comment by davidmarkclements** [comment]
+1 on an example with nan - this would significantly reduce my learning curve.

To my eyes, nans AsyncWorker class is built for single callback execution, whereas an event emitter will trigger callbacks multiple times - I'm not seeing a clear way to do that with nan

**Comment by opensourcegeek** [comment]
@davidmarkclements that's exactly what I was thinking, I'd like to run a long running thread behind the screen which can emit events. I checked on nan project @bnoordhuis suggested to use uv_thread_create for doing something long running instead of NanAsyncWorker. It would be great if nan can abstract that functionality.

**Comment by hokein** [comment]
+1

**Comment by TimZaman** [comment]
What you just need is to use NanAsyncProgressWorker. It's a NanAsyncQueueWorker but with progress callbacks through libuv's uv_async_send functionality. Whenever you call progress->Send(char *, size); it will be caught by your devirtualized function 'HandleProgressCallback()' that will be executed in your main event loop. This can then for example execute a callback that'll invoke something in your .js
