### ISSUE TITLE
Minimal example showing a persistent function callback stored as a class member?

### ISSUE THREAD

**Issue by EvanMachusak** [nodejs/node-addon-examples#53]
Hey guys - I've been struggling to combine example 3 with example 6.  In JavaScript, I'd like the usage to be something like:

`var myObj = new MyObject(function() { console.log("hello world" });`
`myObj.doSomething(); // invoke the callback passed in the ctor`

I've tried:

1. Creating a class member of type `Persistent<Function>`
2. Taking the `Local<Function>` from the ctor args list
3. Calling Reset() on the Persistent member to store a reference to the argument callback and keep it in scope
4.  In doSomething() on the C++ side recreating the callback as a `Local<Function>`, e.g. `New(isolate, this->myPersistent)`

I'm having trouble with 4.  I can't seem to figure out the correct way to rehydrate a callback from a Persistent<Function> in a way where it can actually be invoked.  When trying 4, I receive what I assume is a seg fault as the node process immediately terminates.  I must be doing something wrong but I can't find a snippet anywhere that demonstrates how to do this properly.

Any help would be greatly appreciated.

**Comment by fivdi** [comment]
[This](https://github.com/fivdi/epoll) might help. The constructor ends up [here](https://github.com/fivdi/epoll/blob/master/src/epoll.cc#L174-L184) and later the callback gets called [here](https://github.com/fivdi/epoll/blob/master/src/epoll.cc#L349-L365).

**Comment by EvanMachusak** [comment]
It did!  Thanks.
