### ISSUE TITLE
cannot compile Nan example 7 node v6 (latest)

### ISSUE THREAD

**Issue by Bamieh** [nodejs/node-addon-examples#56]
Hello,
I was trying to compile example 7 with NAN but it fails and gives the following error:

(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

**Comment by eljefedelrodeodeljefe** [comment]
Compiles fine for me on OS X with 6.3.1. I think this rather is a warning, and hence it should be just informative for you or the developer who used this.

Gonna close this for now. If this persists, give me a ping.
