### ISSUE TITLE
Add property example

### ISSUE THREAD

**Issue by xmkevin** [nodejs/node-addon-examples#62]
Can anyone add how to wrap properties on 6_object_wrap, I have tried Nan::SetAccessor，But it has  2 methods, and invoke the wrong function.

Thanks.

**Comment by gabrielschulhof** [comment]
@xmkevin The [N-API version](https://github.com/nodejs/node-addon-examples/blob/master/6_object_wrap/napi/myobject.cc#L21) of the example includes a read/write property. Please reopen this issue if you still need the Nan example updated as well!
