### ISSUE TITLE
Keep this repo? Archive it?

### ISSUE THREAD

**Issue by Trott** [nodejs/node-addon-examples#65]
@rvagg @eljefedelrodeodeljefe Is this repository something that should be maintained? Or archived?  Seems to be pretty dormant.

**Comment by Trott** [comment]
@nodejs/addon-api

**Comment by bnoordhuis** [comment]
Probably can be archived.  The examples were pretty out of date, last I checked, and probably still are.

**Comment by gengjiawen** [comment]
The example is not archived. Should it add to @nodejs/addon-api repository ?
