### ISSUE TITLE
AsyncWorker question pertaining to Execute()

### ISSUE THREAD

**Issue by kevinGodell** [nodejs/node-addon-examples#73]
In the comments for the [async_pi_estimate](https://github.com/nodejs/node-addon-examples/tree/master/async_pi_estimate/node-addon-api) starting at [line 11](https://github.com/nodejs/node-addon-examples/blob/master/async_pi_estimate/node-addon-api/async.cc#L11), there is a part that states "It is not safe to access JS engine data structure..."

- Is this referring to anything that uses info.Env() or does that mean something else? 
- What limitations does that put on data that can be passed in and executed? 
- Will I be able to pass a Napi::Buffer or would I have to convert it to a non-napi value before using it?

My use case is that I have a *node-addon-api* based addon that receives 2 pixel buffers and compares them for differences and then does labeling and blobbing. I will be adding more features to it that will most likely cause it to increase its time to process. My current implementation is synchronous/blocking and I am going to attempt to convert to async.

Any advice or guidance would be appreciated. Thanks.

**Comment by gabrielschulhof** [comment]
@kevinGodell
> Is this referring to anything that uses info.Env() or does that mean something else?

Yes. You must not use any APIs which accept an `info.Env()` from inside `Execute()`.

>  What limitations does that put on data that can be passed in and executed?

You must convert any `Napi::Value` you receive to its native equivalent and store it in the `Napi::AsyncWorker` subclass instance you create before calling `Queue()`. That way the secondary thread on which `Execute` runs accesses only native data.

> Will I be able to pass a Napi::Buffer or would I have to convert it to a non-napi value before using it?

You can use the `Napi::Buffer` class' `Data()` method to obtain a pointer to the native memory segment the buffer wraps. You can store that pointer inside the `Napi::AsyncWorker` subclass instance just as you would other native data. You can then freely access it from `Execute()`. You should perhaps also store a `Napi::Reference<Napi::Buffer>` in the `Napi::AsyncWorker` subclass instance to make sure the JavaScript `Buffer` object is not garbage-collected while the secondary thread is running.

**Comment by kevinGodell** [comment]
Scratch that last question. That is a sub class thing and I understand now. Thanks.
