### ISSUE TITLE
do we need the NPM bindings package as a dependency?

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/node-addon-examples#76]
I am looking here:
https://github.com/nodejs/node-addon-examples/tree/master/1_hello_world/napi

the package.json file looks like:

```json
{
  "name": "hello_world",
  "version": "0.0.0",
  "description": "Node.js Addons Example #1",
  "main": "hello.js",
  "private": true,
  "dependencies": {
    "bindings": "~1.2.1"
  },
  "scripts": {
    "test": "node hello.js"
  },
  "gypfile": true
}
```

but I don't see the reason to have `"bindings": "~1.2.1"` as a dependency? Can I remove it or make it a devDependency?

**Comment by ORESoftware** [comment]
nvm looks like we do need that dependency...kinda weird that this dep is not a core module tho? idk

**Comment by kevinGodell** [comment]
@ORESoftware You do not actually needed. It is just used for convenience. You could directly link to your addon in your js file:
```
const helloLib = require('./build/Release/hello');
```

**Comment by ORESoftware** [comment]
@kevinGodell ahh thanks that's great to know
