### ISSUE TITLE
echo example is need.

### ISSUE THREAD

**Issue by calidion** [nodejs/node-addon-examples#86]
where
```
echo('abc')
```
will produce
```
abc
```

**Comment by helio-frota** [comment]
hi can you please elaborate a bit more what is needed ?
sorry my lack of understanding but it is a JavaScript function that calls a c/c++ function and print out the value of the parameter ?
if yes, then I think this repository already have something similar.
for example this is passing two parameters https://github.com/nodejs/node-addon-examples/blob/master/2_function_arguments/node-addon-api/addon.js#L3

Please let us know if this issue can be closed :+1:
