### ISSUE TITLE
How to get js function in C++ without "Napi::CallbackInfo"?

### ISSUE THREAD

**Issue by zombiecong** [nodejs/node-addon-examples#90]
Hi, 

I have a question about [inherits_from_event_emitter](https://github.com/nodejs/node-addon-examples/blob/master/inherits_from_event_emitter/node-addon-api) example. The example calls "callAndEmit" in js , so I can get info object and find the 'emit' function.But if I try to call "emit" in C++, I am not able to get info object. Is there a way that I can call "emit" in C++?

**Comment by PerspectivesLab** [comment]
did you find any solution ?

**Comment by craterone** [comment]
using [napi asyncwork](https://github.com/nodejs/node-addon-api/blob/main/doc/async_worker.md) solves my problem.
