### ISSUE TITLE
Error: Module did not self-register in centos

### ISSUE THREAD

**Issue by yangjun9772** [nodejs/node-addon-examples#96]
Node: v10.15.3
npm: v6.4.1
OS: centos7-64

Hi, I'm a new one for nodejs.
Now, I was testing the c++ addon examples.
I tried the nan/node-0.1/node-0.2 examples.
And I followed the steps of the Readme.md
But when I run : node hello.js,  it always report error like this:
home/georgeyang/workspace/cmodule/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
 
Please help. BTW, Ibuild the node by the source code.

**Comment by mhdawson** [comment]
@yangjun9772 we are mostly maintaining the napi or node-addon-api examples.  Did you try those?

**Comment by yangjun9772** [comment]
@mhdawson thank you very much for your reply. It works. 
In the first time, I just code by myself and it didn't work.
Now I just "git clone" the example and used the cli
$npm install
$node ./hello.js
And this works.
The example of nan/napi/node-addon-api/node-0.12 OK; the node_0.10 is NG.
So I think I used the wrong way to do the code. And I'll try to study it again.
Thank you so much.
